<?php
// $Id$

/**
 * @file
 *   Module for Crowdsourced Question & Answer
 */

include_once 'crowd_qa.features.inc';

/**
 * Implementation of hook_init().
 */
function crowd_qa_init() {
  // Redirect answer nodes to their question.
  if (arg(0) == 'node' && is_numeric(arg(1)) && arg(2) == NULL) {
    $node = node_load(arg(1));
    if ($node->type == 'crowd_qa_answer') {
      drupal_goto('node/'. $node->field_crowd_qa_question[0]['nid'], NULL, 'answer' . $node->nid);
    }
  }
}


/**
 * Implementation of hook_nodeapi().
 */
function crowd_qa_nodeapi(&$node, $op, $a3, $a4) {
  switch ($op) {
    case 'presave':
      if ($node->type == 'crowd_qa_answer') {
        $question = node_load($node->field_crowd_qa_question[0]['nid']);
        $node->title = 'Answer to "' . $question->title . '"';
      }
  }
}

/**
 * Implementation of hook_form_alter().
 */
function crowd_qa_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'crowd_qa_answer_node_form') {
    // Do not show the nodereference field if it is already set.
    if (isset($form['field_crowd_qa_question'][0]['#default_value']['nid'])) {
      // Hide the question reference widget for already set questions.
      $form['field_crowd_qa_question'][0]['#type'] = 'hidden';
      $form['field_crowd_qa_question'][0]['#value'] = $form['field_crowd_qa_question'][0]['#default_value']['nid'];
      $form['field_crowd_qa_question'][0]['#parents'] = array('field_crowd_qa_question', 0, 'nid');

      // Hide the answer title, this is hard-coded.
      unset($form['title']);

      // Insert the question above the body area.
      $question = node_load($form['field_crowd_qa_question'][0]['#default_value']['nid']);
      $form['question'] = array(
        '#value' => '<h2>Question: ' . l($question->title, 'node/' . $question->nid) . '</h2>',
        '#weight' => -19,
      );

      // Forward the answer post back to the question page.
      $form['#redirect'] = 'node/' . $question->nid;
    }

    $form['preamble'] = array(
      '#value' => '<div class="info">' . t('Please answer properly or not at all.') . '</div>',
      '#weight' => -20,
    );
  }
  elseif ($form_id == 'crowd_qa_question_node_form') {
    $form['preamble'] = array(
      '#value' => '<div class="info">' . t('Please ask a detailed, well-researched question to get good answers quickly.') . '</div>',
      '#weight' => -20,
    );
  }
}

/**
 * Implementation of hook_preprocess_node_form().
 * Provides Atrium-integration for Crowd QA
 */
function crowd_qa_preprocess_node_form(&$vars) {
  if (module_exists('atrium') && !empty($vars['form']['field_crowd_qa_question'])) {
    $vars['sidebar']['field_crowd_qa_question'] = $vars['form']['field_crowd_qa_question'];
    unset($vars['form']['field_crowd_qa_question']);
  }
}


/**
 * Implementation of hook_system_info_alter().
 * Provides Atrium-integration for Crowd QA
 */
function crowd_qa_system_info_alter(&$info, $row) {
  if (module_exists('atrium') && $row->name == 'crowd_qa') {
    if (empty($info['spaces']['types']) || !in_array('og', $info['spaces']['types'])) {
      $info['spaces']['types'][] = 'og';
    }
  }
}